framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict
        # Enable asset mapper in development
        enabled: true

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
