vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        courses:
            uri_prefix: /uploads/courses
            upload_destination: '%kernel.project_dir%/public/uploads/courses'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        avatars:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
